version: '3.8'

services:
  server-go:
    container_name: go
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./test-go:/go
    command: /bin/sh -c "cd /app && ./server"
