services:
  # Servicio para la aplicación web en Go
  app:
    container_name: go-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./test-go:/go
    # working_dir: /go/src/app
    # command: go run main.go
    command: /bin/sh -c "cd /app && ./server"
    # command: go run /go/src/app/test-go/cmd/api/main.go 
    # command: cd /test-go/ ~/go/bin/air
    # command: make dev
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=nappoleon.chat
      - LETSENCRYPT_HOST=nappoleon.chat
      - LETSENCRYPT_EMAIL=tobias.gruponn@gmail.com

  # Nginx Proxy para manejar las peticiones HTTP/HTTPS
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      # - ./nginx.conf:/etc/nginx/nginx.conf
      # - .config/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - DEFAULT_HOST=nappoleon.chat
      - TRUST_DOWNSTREAM_PROXY=false 

  # Let's Encrypt Companion para generar certificados SSL
  nginx-letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-letsencrypt
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=tobias.gruponn@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy
