version: '3.8'

services:
  server-go:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    volumes:
      - ./test-go:/go
    command: /bin/sh -c "cd /app && ./server"