services:
  go-app:
    container_name: go-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./test-go:/go
    command: /bin/sh -c "cd /app && ./server"

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      # - config/nginx.conf:/etc/nginx/nginx.conf
      - certbot-etc:/etc/letsencrypt  # Volumen para los certificados SSL
      - certbot-var:/var/www/certbot 
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - go-app

volumes:
  certbot-etc:
  certbot-var:
