# Usa la imagen base oficial de NGINX
FROM nginx:alpine

# Instala Certbot y dependencias necesarias
RUN apk add --no-cache certbot certbot-nginx bash openssl sudo vim apt

# Instala las dependencias necesarias
# RUN apt-get update && \
#     apt-get install -y sudo vim apt

# # Limpia la caché de apt para reducir el tamaño de la imagen
# RUN apt-get clean && \
#     rm -rf /var/lib/apt/lists/*

# Copia el archivo de configuración NGINX en el contenedor
# COPY config/nginx.conf /etc/nginx/nginx.conf

# Expone los puertos 80 y 443 para HTTP y HTTPS
EXPOSE 80 443

# Comando para iniciar NGINX
CMD ["nginx", "-g", "daemon off;"]
