version: '3.8'

services:
  server-go:
    container_name: go
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    volumes:
      - ./test-go:/go
    command: /bin/sh -c "cd /app && ./server"

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server-go
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
